config_version: 2.0
spawn_rate:
  how_many: 2
  how_often: 400
  default_max: 0
angels:
  worlds:
    world: 20
  teleport_worlds:
    - world
  freeze_time: 100
  weapon: DIAMOND_PICKAXE
  drops:
    - COBBLESTONE
    - STONE
  angels_can_steal: true
  can_build: true
  spawn_from_chat:
    enabled: true
    chance: 50
    distance_from_player: 10
cybermen:
  worlds:
    world: 10
  drops:
    - REDSTONE
    - STONE_BUTTON
  can_upgrade: true
daleks:
  worlds:
    world: 20
  drops:
    - SLIME_BALL
    - ROTTEN_FLESH
empty_child:
  worlds:
    world: 10
  drops:
    - COOKED_BEEF
    - SUGAR
hath:
  worlds:
    world: 10
  drops:
    - SALMON
    - STONE_PICKAXE
ice_warriors:
  worlds:
    world: 20
  drops:
    - ICE
    - PACKED_ICE
    - SNOW_BLOCK
k9:
  by_taming: true
  can_build: true
  worlds:
    world: true
silurians:
  worlds:
    world: 20
  drops:
    - GOLD_NUGGET
    - FEATHER
ood:
  worlds:
    world: true
  drops:
    - NAME_TAG
  spawn_from_villager: 20
  spawn_from_cured: 5
judoon:
  guards: true
  can_build: true
  ammunition: 25
  damage: 4
  worlds:
    world: 20
sontarans:
  worlds:
    world: 20
  drops:
    - POTATO
    - MILK_BUCKET
  can_tame: true
toclafane:
  spawn_from_bee: 5
  destroy_blocks: true
  worlds:
    world: 20
  drops:
    - GUNPOWDER
    - HONEYCOMB
vashta_nerada:
  worlds:
    world: 10
  drops:
    - BONE
    - LEATHER
zygons:
  worlds:
    world: 10
  drops:
    - PAINTING
    - SAND
silent:
  worlds:
    world: 10
  drops:
    - INK_SAC
    - FLOWER_POT
